-- MySQL Workbench Synchronization
-- Generated: 2016-06-21 12:29
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: mpayet

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `mydb`.`caso_de_uso`
CHANGE COLUMN `descripcion` `descripcion` VARCHAR(500) NOT NULL ;

ALTER TABLE `mydb`.`actor`
CHANGE COLUMN `descripcion` `descripcion` VARCHAR(500) NULL DEFAULT NULL ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
