SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `mydb`.`estimacion`
CHANGE COLUMN `numestimacion` `numestimacion` INT(11) NOT NULL AFTER `idestimacion`,
CHANGE COLUMN `numfase` `numfase` INT(11) NOT NULL AFTER `numestimacion`,
ADD UNIQUE INDEX `numero` (`numestimacion` ASC, `numfase` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
