-- MySQL Workbench Synchronization
-- Generated: 2016-08-09 11:33
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: mpayet

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `mydb`.`actor`
DROP FOREIGN KEY `fk_actor_plataforma1`;

ALTER TABLE `mydb`.`actor`
DROP COLUMN `idplataforma`,
DROP INDEX `fk_actor_plataforma1_idx` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
